ERROR: Assertion 'false', in file assert-fail1-test.scad, line 1
TRACE: was called by module 'assert', in file assert-fail1-test.scad, line 1.
